"""
InternShield CSCC — AI Engine
==============================
File 3 of 5.

This is the "heavy duty, durable" AI layer. It merges what used to be
base.py + openai_provider.py + shellgpt.py + prompts/templates.py +
the ai/__init__.py factory, and adds two brand-new pieces that make
the whole tool resilient even on a free/limited-token API tier:

    1. AnthropicProvider  — talks to the Claude API directly (Messages
                             endpoint), using a small/cheap model by
                             default so a free-tier key's token budget
                             lasts as long as possible.
    2. OfflineAdvisor      — a zero-cost, zero-network, rule-based
                             fallback. If NO API key and NO shell-gpt
                             are available, the tool still produces
                             useful advisory text instead of crashing
                             or silently doing nothing.

IMPORTANT — ABOUT API KEYS:
    No real API key is (or should ever be) hardcoded in this file or
    anywhere in this repo. You supply your own key(s) in `.env`
    (copied from `.env.example`). This is standard practice — a key
    baked into source code is a leaked key the moment the repo is
    pushed to GitHub. `.env` is already git-ignored for you.

The `AIProviderFactory` / `resolve_error()` helpers implement a
FALLBACK CHAIN:  shellgpt -> openai -> anthropic -> offline
so a single missing tool or expired key never takes the whole
feature down — it just degrades gracefully to the next option.
"""

from __future__ import annotations

import subprocess
from abc import ABC, abstractmethod
from typing import Optional, List

from core_engine import (
    Finding,
    AssessmentSummary,
    log,
    settings,
    ToolMissingError,
    AIProviderError,
)

try:
    import requests
except ImportError:
    requests = None


# ======================================================================
# PROMPT TEMPLATES
# ======================================================================

FINDING_ANALYSIS_PROMPT = """You are a Principal Cloud Security Engineer and DevSecOps Architect.
Review the following security finding generated by an automated scanner.

Your objective is to provide:
1. A brief, 2-sentence explanation of the real-world risk.
2. The exact, safe CLI commands (AWS CLI or Docker) or configuration changes needed to remediate this issue.

CRITICAL SAFETY RULE: You are an advisory tool. Provide the commands as text for a human to review. Do NOT attempt to execute them.

--- FINDING DATA ---
{finding_json}
--------------------

FORMAT YOUR RESPONSE AS:
**Risk Analysis:** [Your analysis]

**Remediation Action:**
[Your CLI commands or config snippets in markdown code blocks]
"""

EXECUTIVE_SUMMARY_PROMPT = """You are a Virtual Chief Information Security Officer (vCISO).
Review the following metrics from a recent Cloud Security Assessment.

Write a 2-paragraph executive summary highlighting the most critical risks and the overall security posture of the environment. Maintain a professional, objective tone. Do not use fear-mongering language.

--- ASSESSMENT METRICS ---
{summary_json}
--------------------------
"""

ERROR_RESOLUTION_PROMPT = """I am running a cloud security bash/python tool called InternShield CSCC and hit this terminal error:

'{error_msg}'

Explain in simple, plain language why this happened, then give the EXACT command(s) or config change needed to fix it.
Keep it under 8 lines. Be concrete, not generic.
"""


# ======================================================================
# ABSTRACT BASE
# ======================================================================

class AIProvider(ABC):
    """The base contract for any LLM acting as a Cloud Security Analyst."""

    name: str = "base"

    @abstractmethod
    def health_check(self) -> bool:
        """Verifies if the AI provider is authenticated and accessible."""
        pass

    @abstractmethod
    def analyze_finding(self, finding: Finding) -> Optional[str]:
        pass

    @abstractmethod
    def generate_executive_summary(self, summary: AssessmentSummary) -> Optional[str]:
        pass

    def resolve_cli_error(self, error_msg: str) -> Optional[str]:
        """Default error-resolution path shared by every provider that
        can do free-form text generation. Providers may override this."""
        raise NotImplementedError


# ======================================================================
# SHELL-GPT PROVIDER (local `sgpt` CLI — no code-level API key needed,
# sgpt manages its own key/config independently)
# ======================================================================

class ShellGPTProvider(AIProvider):
    name = "shellgpt"

    def __init__(self):
        if not self.health_check():
            raise ToolMissingError(
                "Shell-GPT (sgpt) is not installed or not in PATH. "
                "Install it using: pip install shell-gpt"
            )

    def health_check(self) -> bool:
        try:
            result = subprocess.run(["sgpt", "--version"], capture_output=True, text=True, check=True)
            return "sgpt" in result.stdout.lower() or result.returncode == 0
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    def analyze_finding(self, finding: Finding) -> Optional[str]:
        prompt = FINDING_ANALYSIS_PROMPT.format(finding_json=finding.model_dump_json(indent=2))
        return self._call_sgpt(prompt)

    def generate_executive_summary(self, summary: AssessmentSummary) -> Optional[str]:
        metrics_json = summary.model_dump_json(exclude={"findings"}, indent=2)
        prompt = EXECUTIVE_SUMMARY_PROMPT.format(summary_json=metrics_json)
        return self._call_sgpt(prompt)

    def resolve_cli_error(self, error_msg: str) -> Optional[str]:
        log.info("[cyan]Asking Shell-GPT for an error resolution...[/cyan]")
        prompt = ERROR_RESOLUTION_PROMPT.format(error_msg=error_msg)
        return self._call_sgpt(prompt)

    def _call_sgpt(self, prompt: str) -> Optional[str]:
        cmd = ["sgpt", "--no-cache", prompt]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            if result.returncode != 0:
                log.error(f"Shell-GPT returned an error: {result.stderr.strip()}")
                return None
            return result.stdout.strip()
        except subprocess.TimeoutExpired:
            log.warning("Shell-GPT request timed out after 60 seconds.")
            return None
        except Exception as e:
            log.error(f"Failed to communicate with Shell-GPT: {str(e)}")
            return None


# ======================================================================
# OPENAI PROVIDER (direct HTTPS call — no heavy SDK dependency)
# ======================================================================

class OpenAIProvider(AIProvider):
    name = "openai"

    def __init__(self):
        if requests is None:
            raise AIProviderError("The 'requests' package is not installed. Run: pip install -r requirement.txt")
        self.api_key = settings.get_ai_api_key("openai")
        self.model = settings.ai.openai_model
        if not self.health_check():
            raise AIProviderError("OpenAI API Key is missing or invalid (check OPENAI_API_KEY in .env).")

    def health_check(self) -> bool:
        return bool(self.api_key and self.api_key.startswith("sk-"))

    def analyze_finding(self, finding: Finding) -> Optional[str]:
        prompt = FINDING_ANALYSIS_PROMPT.format(finding_json=finding.model_dump_json(indent=2))
        return self._call_api(prompt, system_role="You are a Principal Cloud Security Engineer.")

    def generate_executive_summary(self, summary: AssessmentSummary) -> Optional[str]:
        metrics_json = summary.model_dump_json(exclude={"findings"}, indent=2)
        prompt = EXECUTIVE_SUMMARY_PROMPT.format(summary_json=metrics_json)
        return self._call_api(prompt, system_role="You are a vCISO.")

    def resolve_cli_error(self, error_msg: str) -> Optional[str]:
        prompt = ERROR_RESOLUTION_PROMPT.format(error_msg=error_msg)
        return self._call_api(prompt, system_role="You are a calm, precise DevOps troubleshooting assistant.")

    def _call_api(self, prompt: str, system_role: str) -> Optional[str]:
        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_role},
                {"role": "user", "content": prompt},
            ],
            # Keep it small/cheap for free or limited-token tiers.
            "max_tokens": 500,
            "temperature": 0.2,
        }
        try:
            log.debug(f"Sending request to OpenAI API (model={self.model})...")
            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers, json=payload, timeout=30,
            )
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"].strip()
        except requests.exceptions.RequestException as e:
            log.error(f"OpenAI API request failed: {str(e)}")
            return None


# ======================================================================
# ANTHROPIC / CLAUDE PROVIDER (direct HTTPS call to the Messages API)
# ======================================================================

class AnthropicProvider(AIProvider):
    """Talks to Claude directly via the Anthropic Messages API.
    Uses a small/cheap default model so a free or limited-token key
    goes as far as possible."""

    name = "anthropic"
    API_URL = "https://api.anthropic.com/v1/messages"
    API_VERSION = "2023-06-01"

    def __init__(self):
        if requests is None:
            raise AIProviderError("The 'requests' package is not installed. Run: pip install -r requirement.txt")
        self.api_key = settings.get_ai_api_key("anthropic")
        self.model = settings.ai.anthropic_model
        if not self.health_check():
            raise AIProviderError("Anthropic API Key is missing or invalid (check ANTHROPIC_API_KEY in .env).")

    def health_check(self) -> bool:
        return bool(self.api_key and self.api_key.startswith("sk-ant-"))

    def analyze_finding(self, finding: Finding) -> Optional[str]:
        prompt = FINDING_ANALYSIS_PROMPT.format(finding_json=finding.model_dump_json(indent=2))
        return self._call_api(prompt, system_role="You are a Principal Cloud Security Engineer.")

    def generate_executive_summary(self, summary: AssessmentSummary) -> Optional[str]:
        metrics_json = summary.model_dump_json(exclude={"findings"}, indent=2)
        prompt = EXECUTIVE_SUMMARY_PROMPT.format(summary_json=metrics_json)
        return self._call_api(prompt, system_role="You are a vCISO.")

    def resolve_cli_error(self, error_msg: str) -> Optional[str]:
        prompt = ERROR_RESOLUTION_PROMPT.format(error_msg=error_msg)
        return self._call_api(prompt, system_role="You are a calm, precise DevOps troubleshooting assistant.")

    def _call_api(self, prompt: str, system_role: str) -> Optional[str]:
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": self.API_VERSION,
            "content-type": "application/json",
        }
        payload = {
            "model": self.model,
            "max_tokens": 500,
            "system": system_role,
            "messages": [{"role": "user", "content": prompt}],
        }
        try:
            log.debug(f"Sending request to Anthropic API (model={self.model})...")
            response = requests.post(self.API_URL, headers=headers, json=payload, timeout=30)
            response.raise_for_status()
            data = response.json()
            parts = data.get("content", [])
            text = "".join(p.get("text", "") for p in parts if p.get("type") == "text")
            return text.strip() or None
        except requests.exceptions.RequestException as e:
            log.error(f"Anthropic API request failed: {str(e)}")
            return None


# ======================================================================
# OFFLINE ADVISOR — zero network, zero API key, always available.
# This is what makes the tool durable: it NEVER hard-fails just
# because the internet or a key isn't there.
# ======================================================================

class OfflineAdvisor(AIProvider):
    name = "offline"

    _KNOWLEDGE_BASE = [
        ("no such file", "The file/path referenced doesn't exist. Check the path and current working directory (`pwd`, `ls`)."),
        ("permission denied", "The current user lacks OS-level permission. Try `chmod +x <file>` for scripts, or re-run with the correct user (avoid `sudo` unless truly required)."),
        ("modulenotfounderror", "A Python package is missing. Activate your virtual environment and run: pip install -r requirement.txt"),
        ("no module named", "A Python package is missing. Activate your virtual environment and run: pip install -r requirement.txt"),
        ("nocredentialserror", "AWS credentials were not found. Run `aws configure` or set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY in your .env."),
        ("accessdenied", "Your AWS identity lacks the IAM permission for this API call. Attach a read-only policy such as `SecurityAudit` or `ReadOnlyAccess`."),
        ("trivy", "Trivy isn't installed or not on PATH. Install it: https://aquasecurity.github.io/trivy/latest/getting-started/installation/"),
        ("sgpt", "Shell-GPT isn't installed or configured. Run: pip install shell-gpt && sgpt --install-integration"),
        ("api key", "An AI API key is missing or invalid. Copy .env.example to .env and set OPENAI_API_KEY or ANTHROPIC_API_KEY."),
        ("timeout", "The request took too long — check your network connection, or the remote service may be rate-limiting you. Try again shortly."),
        ("connectionerror", "Could not reach the network/API endpoint. Check your internet connection or firewall/proxy settings."),
        ("yaml", "config.yaml has a syntax error. Compare it against config.example.yaml and fix the indentation/keys."),
        ("json", "A response could not be parsed as valid JSON — the upstream tool may have printed an unexpected message alongside its output."),
    ]

    def health_check(self) -> bool:
        return True  # Always available — no external dependency at all.

    def analyze_finding(self, finding: Finding) -> Optional[str]:
        return (
            f"[Offline mode — no AI key/tool configured]\n"
            f"Risk: {finding.impact}\n"
            f"Suggested fix: {finding.recommendation}\n"
            f"(Set OPENAI_API_KEY, ANTHROPIC_API_KEY, or install shell-gpt for deeper AI analysis.)"
        )

    def generate_executive_summary(self, summary: AssessmentSummary) -> Optional[str]:
        return (
            f"[Offline mode — no AI key/tool configured]\n"
            f"This assessment of '{summary.target_environment}' produced {summary.total_findings} findings: "
            f"{summary.critical_count} Critical, {summary.high_count} High, {summary.medium_count} Medium, "
            f"{summary.low_count} Low. Prioritize Critical and High findings first — they represent the "
            f"highest-likelihood paths to compromise or data exposure."
        )

    def resolve_cli_error(self, error_msg: str) -> Optional[str]:
        lowered = error_msg.lower()
        for keyword, advice in self._KNOWLEDGE_BASE:
            if keyword in lowered:
                return (
                    f"[Offline error-resolver — matched pattern: '{keyword}']\n"
                    f"{advice}\n\n"
                    f"Raw error: {error_msg.strip()[:300]}"
                )
        return (
            "[Offline error-resolver — no exact pattern matched]\n"
            "General checklist: (1) is the virtual environment activated? "
            "(2) did `pip install -r requirement.txt` complete successfully? "
            "(3) check logs/errors.log for the full traceback.\n\n"
            f"Raw error: {error_msg.strip()[:300]}"
        )


# ======================================================================
# FACTORY + FALLBACK CHAIN
# ======================================================================

_PROVIDER_MAP = {
    "shellgpt": ShellGPTProvider,
    "openai": OpenAIProvider,
    "anthropic": AnthropicProvider,
    "claude": AnthropicProvider,
    "offline": OfflineAdvisor,
}

# Order used by "auto" mode and by the global error resolver.
_FALLBACK_ORDER = ["shellgpt", "openai", "anthropic", "offline"]


class AIProviderFactory:
    """Factory to instantiate the configured AI Provider(s)."""

    @staticmethod
    def create(provider_name: str) -> AIProvider:
        provider_class = _PROVIDER_MAP.get(provider_name.lower())
        if not provider_class:
            raise ValueError(f"AI Provider '{provider_name}' is not supported.")
        return provider_class()

    @staticmethod
    def create_first_available(order: Optional[List[str]] = None) -> AIProvider:
        """Tries each provider in `order` and returns the first one that
        initializes successfully. OfflineAdvisor is always last and
        always succeeds, so this method never raises."""
        for name in (order or _FALLBACK_ORDER):
            try:
                provider = AIProviderFactory.create(name)
                log.info(f"AI Engine: using provider '[green]{provider.name}[/green]'")
                return provider
            except Exception as e:
                log.debug(f"AI provider '{name}' unavailable: {e}")
                continue
        return OfflineAdvisor()


def get_configured_provider() -> Optional[AIProvider]:
    """Resolves the AI provider based on config.yaml's ai.default_provider.
    Returns None only if the user explicitly set 'disabled'."""
    provider_name = settings.ai.default_provider.lower()
    if provider_name == "disabled":
        return None
    if provider_name == "auto":
        return AIProviderFactory.create_first_available()
    try:
        return AIProviderFactory.create(provider_name)
    except Exception as e:
        log.warning(f"AI Provider '{provider_name}' failed to initialize: {e}. Falling back to 'auto' chain.")
        return AIProviderFactory.create_first_available()


def resolve_error(error_msg: str) -> str:
    """The heart of the 'self-healing CLI' requirement: whenever
    anything in the tool fails, call this to get a plain-language
    explanation + fix, trying shellgpt -> openai -> anthropic ->
    offline until one of them returns something useful.
    """
    for name in _FALLBACK_ORDER:
        try:
            provider = AIProviderFactory.create(name)
        except Exception:
            continue
        try:
            result = provider.resolve_cli_error(error_msg)
        except NotImplementedError:
            continue
        if result:
            return result
    # This line should be unreachable since OfflineAdvisor always
    # returns something, but it's kept as an absolute last resort.
    return f"Unable to auto-resolve this error. Raw error: {error_msg.strip()[:300]}"
